name: mapbox_gl
description: A Flutter plugin for integrating Mapbox Maps inside a Flutter application on Android, iOS and web platfroms.
version: 0.16.2
homepage: https://github.com/picap-inc/maps.git

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/picap-inc/maps.git
      path: mapbox_gl_platform_interface
      ref: android-15
  mapbox_gl_web:
    git:
      url: https://github.com/picap-inc/maps.git
      path: mapbox_gl_web
      ref: android-15
  collection: 1.18.0

dependency_overrides:
  mapbox_gl_platform_interface:
    path: ./mapbox_gl_platform_interface
  mapbox_gl_web:
    path: ./mapbox_gl_web

flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
      web:
        default_package: mapbox_gl_web

environment:
  sdk: ^3.5.0
  flutter: ^3.24.3
