name: mapbox_gl_platform_interface
description: A common platform interface for the mapbox_gl plugin.
version: 0.16.0
homepage: https://github.com/tobrun/flutter-mapbox-gl

dependencies:
  flutter:
    sdk: flutter
  meta: 1.15.0

environment:
  sdk: ^3.5.0
  flutter: ^3.24.3
