name: mapbox_gl_web
description: Web platform implementation of mapbox_gl
version: 0.16.0
homepage: https://github.com/picap-inc/maps

publish_to: 'none'

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.16.0
  mapbox_gl_platform_interface:
    path: ../mapbox_gl_platform_interface
  mapbox_gl_dart: ^0.2.1
  image: '>=3.0.0 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"
